---
# Variables that can be used that are set as fact by role common-decode-extravars-setfacts
# apollo_full_domain_name
# apollo_short_machine_name 
# apollo_padded_number 
nfs_apollo_host_name: "{{ apollo_short_machine_name }}"
nfs_apollo_dir_name: "{{ apollo_short_machine_name }}"
nfs_apollo_user_name: "apollo{{ apollo_padded_number }}_user"
nfs_apollo_user_id: "16{{ apollo_padded_number }}"
nfs_mount_point: /mnt/user-data # the root of the filesystem
nfs_export_root: /srv/export/data/nectar
nfs_apollo_user_data_root: "{{ nfs_mount_point }}/nectar" # /mnt/user-data//nectar equivalent to /srv/export/data/nectar
nfs_quota_root: "{{ nfs_mount_point }}"
nfs_apollo_user_dir: "{{ nfs_apollo_user_data_root }}/{{ nfs_apollo_dir_name }}"
nfs_apollo_user_quota: "1024G 2048G 3350000 6700000"
nfs_apollo_user_gid: 987 # tomcat GID on ubuntu 24.04

