
# Install the following roles and collections from the Ansible Galaxy hub at galaxy.ansible.com
# Install collections with
#     ansible-galaxy collection install -r requirements.yml
# Install roles with
#     ansible-galaxy roles install -r requirements.yml
# Install collections and roles with:
#     ansible-galaxy install -r requirements.yml

collections:
  - name: ansible.posix
  - name: community.general

roles:
  # install ansible install role
  - src: geerlingguy.ansible
  # install git install role
  - src: geerlingguy.git
  # install postgresql install role
  - src: geerlingguy.postgresql
  # install docker/docker-compose install role
  - src: geerlingguy.docker

