{
 "title": "Apollo Infrastructure VM Overview",
 "description": "Apollo Infrastructure VM stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "hosts",
    "query": "label_values(node_load1, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "apollo-backup (Load Averages)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance='apollo-backup:9100'}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{instance='apollo-backup:9100'}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{instance='apollo-backup:9100'}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "apollo-user-nfs (Load Averages)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance='apollo-user-nfs:9100'}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{instance='apollo-user-nfs:9100'}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{instance='apollo-user-nfs:9100'}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "apollo-monitor (Load Averages)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance='apollo-monitor:9100'}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{instance='apollo-monitor:9100'}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{instance='apollo-monitor:9100'}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "apollo-portal (Load Averages)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance='apollo-portal:9100'}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{instance='apollo-portal:9100'}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{instance='apollo-portal:9100'}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "apollo-user-jbrowse (Load Averages)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance='apollo-user-jbrowse:9100'}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{instance='apollo-user-jbrowse:9100'}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{instance='apollo-user-jbrowse:9100'}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "apollo-backup (CPU Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode='idle',instance='apollo-backup:9100'}[5m])))*100",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "apollo-user-nfs (CPU Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode='idle',instance='apollo-user-nfs:9100'}[5m])))*100",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "apollo-monitor (CPU Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode='idle',instance='apollo-monitor:9100'}[5m])))*100",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "apollo-portal (CPU Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode='idle',instance='apollo-portal:9100'}[5m])))*100",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "apollo-user-jbrowse (CPU Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode='idle',instance='apollo-user-jbrowse:9100'}[5m])))*100",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "apollo-backup (Memory Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance='apollo-backup:9100'} - node_memory_MemAvailable_bytes{instance='apollo-backup:9100'})/1024/1024",
     "legendFormat": "Used Mem"
    }
   ]
  },
  {
   "title": "apollo-user-nfs (Memory Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance='apollo-user-nfs:9100'} - node_memory_MemAvailable_bytes{instance='apollo-user-nfs:9100'})/1024/1024",
     "legendFormat": "Used Mem"
    }
   ]
  },
  {
   "title": "apollo-monitor (Memory Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance='apollo-monitor:9100'} - node_memory_MemAvailable_bytes{instance='apollo-monitor:9100'})/1024/1024",
     "legendFormat": "Used Mem"
    }
   ]
  },
  {
   "title": "apollo-portal (Memory Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance='apollo-portal:9100'} - node_memory_MemAvailable_bytes{instance='apollo-portal:9100'})/1024/1024",
     "legendFormat": "Used Mem"
    }
   ]
  },
  {
   "title": "apollo-user-jbrowse (Memory Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance='apollo-user-jbrowse:9100'} - node_memory_MemAvailable_bytes{instance='apollo-user-jbrowse:9100'})/1024/1024",
     "legendFormat": "Used Mem"
    }
   ]
  },
  {
   "title": "apollo-backup (Disk Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance='apollo-backup:9100',mountpoint='/'} / node_filesystem_size_bytes{instance='apollo-backup:9100',mountpoint='/'} * 100)",
     "legendFormat": "Disk %"
    }
   ]
  },
  {
   "title": "apollo-user-nfs (Disk Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance='apollo-user-nfs:9100',mountpoint='/'} / node_filesystem_size_bytes{instance='apollo-user-nfs:9100',mountpoint='/'} * 100)",
     "legendFormat": "Disk %"
    }
   ]
  },
  {
   "title": "apollo-monitor (Disk Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance='apollo-monitor:9100',mountpoint='/'} / node_filesystem_size_bytes{instance='apollo-monitor:9100',mountpoint='/'} * 100)",
     "legendFormat": "Disk %"
    }
   ]
  },
  {
   "title": "apollo-portal (Disk Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance='apollo-portal:9100',mountpoint='/'} / node_filesystem_size_bytes{instance='apollo-portal:9100',mountpoint='/'} * 100)",
     "legendFormat": "Disk %"
    }
   ]
  },
  {
   "title": "apollo-user-jbrowse (Disk Usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance='apollo-user-jbrowse:9100',mountpoint='/'} / node_filesystem_size_bytes{instance='apollo-user-jbrowse:9100',mountpoint='/'} * 100)",
     "legendFormat": "Disk %"
    }
   ]
  },
  {
   "title": "apollo-backup (Network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!='lo',instance='apollo-backup:9100'}[5m])",
     "legendFormat": "Rx"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!='lo',instance='apollo-backup:9100'}[5m])",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "apollo-user-nfs (Network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!='lo',instance='apollo-user-nfs:9100'}[5m])",
     "legendFormat": "Rx"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!='lo',instance='apollo-user-nfs:9100'}[5m])",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "apollo-monitor (Network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!='lo',instance='apollo-monitor:9100'}[5m])",
     "legendFormat": "Rx"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!='lo',instance='apollo-monitor:9100'}[5m])",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "apollo-portal (Network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!='lo',instance='apollo-portal:9100'}[5m])",
     "legendFormat": "Rx"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!='lo',instance='apollo-portal:9100'}[5m])",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "apollo-user-jbrowse (Network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!='lo',instance='apollo-user-jbrowse:9100'}[5m])",
     "legendFormat": "Rx"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!='lo',instance='apollo-user-jbrowse:9100'}[5m])",
     "legendFormat": "Tx"
    }
   ]
  }
 ]
}