---
#NOTE nginx service has to be restarted after manually obtaining certificates!!!
- name: "install ngnix using apt"
  apt:
    name: "nginx"
    state: "latest"
    update_cache: yes

- name: "Allow HTTP(S) connections to Nginx"
  ufw:
    rule: allow
    name: 'Nginx Full'

