---
- name: "install ngnix using apt"
  apt:
    name: "nginx"
    state: "latest"
    update_cache: yes

- name: "Place nginx conf file from template"
  template:
    src: "apollo-00X.genome.edu.au"
    dest: "{{nginx_config_file_path}}"
    force: yes
    backup: no
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  vars:
    template_nginx_domain: "{{nginx_domain}}"
  when: certbot_installed is defined and certbot_installed

- name: "Create symbolic link in enabled-sites to available-sites conf"
  file:
    src: "{{nginx_config_file_path}}"
    dest: "{{nginx_slink_file_path}}"
    state: link
    force: yes

- name: "Create site root directory"
  file:
    path: "{{nginx_site_root_dir}}"
    state: directory
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

- name: "Place index html file from template"
  template:
    src: "index.html"
    dest: "{{nginx_index_file_path}}"
    force: yes
    backup: no
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"

- name: "Create symbolic link for index html"
  file:
    src: "{{nginx_root_index}}"
    dest: "{{nginx_index_file_path}}"
    state: link
    force: yes

- name: "Change group to www-data and mode to g+w in /var/www directory"
  file:
    path: "/var/www"
    state: directory
    group: "www-data"
    mode: "g+w"
    recurse: yes

- name: "Remove default nginx vhost config file"
  file:
    path: "{{nginx_default_conf_file_path}}"
    state: absent
