---
- name: "check that dir {{apollo_data_dir_path}} exists and register result"
  stat: "path={{apollo_data_dir_path}}"
  register: "stat_result"

# This role will be revisited when role for mounting NFS export is created and may be removed or merged into the new NFS role   
- name: "Create dir {{apollo_data_dir_path}} stat_result.stat.exists = {{stat_result.stat.exists}}"
  file:
    path: "{{apollo_data_dir_path}}"
    state: "directory"
    owner: "tomcat"
    group: "tomcat"
    mode: "02775"
    recurse: yes
  when: "stat_result.stat.exists == false"