- name: Set timestamp for backup filename
  ansible.builtin.set_fact:
    alertmanager_backup_suffix: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: Back up existing Alertmanager config with timestamp
  ansible.builtin.copy:
    src: "{{ alertmanager_config_path }}"
    dest: "{{ alertmanager_config_path }}.{{ alertmanager_backup_suffix }}"
    remote_src: true
    force: yes
  when: alertmanager_config_path is file
  tags: backup

- name: Configure default environment for Alertmanager
  copy:
    dest: /etc/default/prometheus-alertmanager
    content: |
      ARGS="--config.file={{ alertmanager_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart prometheus-alertmanager

- name: Install Alertmanager configuration
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config_path }}"
    owner: prometheus
    group: prometheus
    mode: "0644"
  notify: Restart prometheus-alertmanager

