---
- name: "Include JBrowse dependencies variables"
  include_vars:
    file: "jbrowse_deps.yml"

- name: "install JBrowse dependencies"
  apt:
    pkg: "{{ jbrowse_deps }}"
    state: present
    update_cache: yes

