---
util_packages:
    - vim
    - ssl-cert
    - lsb-release
    - curl
    - wget
    - netcat-traditional
    - git
    - zip
    - unzip
    - build-essential
    - gnupg2
    - atop
    - iotop
    - htop
    - net-tools
    - nmap
    - speedometer
    - iperf3
    - tree
    - plocate
    - ack-grep
    - fasd
    - ranger
    - byobu
    - glances
    - duf
    - xkcdpass
    - python3-passlib

