---
- name: "Install Nagios NRPE Server"
  apt:
    name: "nagios-nrpe-server"
    state: "present"
    update_cache: yes

- name: "Install Nagios Plugins"
  apt:
    name: "nagios-plugins"
    state: "present"
    update_cache: yes

- name: "Allow NRPE from nagios server"
  ufw:
    rule: allow
    proto: tcp 
    port: '5666'
    src: '{{ nagios_server }}'

- name: "Get ip address in current host {{inventory_hostname}}"
  shell: "hostname -I | awk '{print $1}'"
  register: "current_host_ip_address"
  ignore_errors: true

- name: "Place nrpe.cfg template in {{nagios_nrpe_file_path}} directory IP {{current_host_ip_address.stdout}}"
  template:
    src: "nrpe.cfg"
    dest: "{{nagios_nrpe_file_path}}"
    force: yes
    backup: no
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  vars:
    host_ip_address: "{{current_host_ip_address.stdout}}"
    allowed_hosts_ips: "{{nagios_allowed_hosts_ips}}"

- name: "Place nrpe_local.cfg template in {{nagios_nrpe_file_path}}"
  template:
    src: "nrpe_local.cfg"
    dest: "{{nagios_nrpe_file_path}}"
    force: yes
    backup: no
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: "Restart nagios nrpe service"
  systemd:
    state: "restarted"
    name: "nagios-nrpe-server"
  when: not ansible_check_mode

