---
# TODO comment if running individually need to enter extravars value of apollo_full_domain_name
nginx_set_conf_full_domain_name: "{{ apollo_full_domain_name }}"
nginx_set_conf_root_index: "/var/www/html/index.nginx-debian.html" 
nginx_set_conf_available_dir: "/etc/nginx/sites-available"
nginx_set_conf_enabled_dir: "/etc/nginx/sites-enabled"
