---
- name: "Include monotoring server variables"
  include_vars:
    file: "prometheus_exporters.yml"

- name: "Add key for prometheus packages"
  apt_key:
    url: https://s3-eu-west-1.amazonaws.com/deb.robustperception.io/41EFC99D.gpg
    state: present

- name: "Install prometheus exporters"
  apt: 
    name: '{{ prometheus_exporters }}'
    state: present
    update_cache: yes

