---
- name: "Print user name and user id to be created"
  debug: 
    msg: "User Name = {{create_user_name}} - User Id = {{create_user_id}}"

# Creating the user without password and without ssh keys is equivalent to option --disabled-login
- name: "Create user account in NFS server"
  user:
    name: "{{create_user_name}}"
    uid: "{{create_user_id}}"
    shell: "/bin/false"
    create_home: "no"
    state: "present"

