---
prometheus_exporters:
  - prometheus-node-exporter
  - prometheus-postgres-exporter
  - prometheus-pushgateway
  - prometheus-alertmanager

prometheus_url_key: "https://s3-eu-west-1.amazonaws.com/deb.robustperception.io/41EFC99D.gpg"





