---
- name: "Connect to docker container and check if extension {{apollo_cmd_select_count_extension}} already exists in postgres database"
  command: "{{apollo_cmd_section_1}} {{apollo_cmd_select_count_extension}}"
  register: "extension_exists"

- name: "Print command executed from the previous task 1"
  debug:
    msg: "{{apollo_cmd_section_1}} {{apollo_cmd_select_count_extension}}"

- name: "Create extension {{apollo_extname}} extension_exists.stdout = {{extension_exists.stdout}}"
  command: "{{apollo_cmd_section_1}} {{apollo_cmd_create_extension}}"
  when: extension_exists.stdout == "0"

- name: "Print command executed from the previous task 2"
  debug:
    msg: "{{apollo_cmd_section_1}} {{apollo_cmd_create_extension}}"

- name: "Connect to docker container and check if Admin user already exists in postgres database"
  command: "{{apollo_cmd_section_1}} {{apollo_cmd_select_count_username}}"
  register: "user_exists"

- name: "Print command executed from the previous task 3"
  debug:
    msg: "{{apollo_cmd_section_1}} {{apollo_cmd_select_count_username}}"

- name: "Insert row in grails_user table in postgres database {{apollo_dbname}} user_exists.stdout = {{user_exists.stdout}}"
  command: "{{apollo_cmd_section_1}} {{apollo_cmd_insert_grails_user_1}} {{apollo_cmd_insert_grails_user_2}} {{apollo_cmd_insert_grails_user_3}}"
  when: user_exists.stdout == "0"

- name: "Print command executed from the previous task 4"
  debug:
    msg: "{{apollo_cmd_section_1}} {{apollo_cmd_insert_grails_user_1}} {{apollo_cmd_insert_grails_user_2}} {{apollo_cmd_insert_grails_user_3}}"

- name: "Insert row in grails_user_roles table in postgres database {{apollo_dbname}} db_exists.stdout = {{db_exists.stdout}}"
  command: "{{apollo_cmd_section_1}} {{apollo_cmd_insert_grails_user_roles_1}} {{apollo_cmd_insert_grails_user_roles_2}}"
  when: user_exists.stdout == "0"

- name: "Print command executed from the previous task 5"
  debug:
    msg: "{{apollo_cmd_section_1}} {{apollo_cmd_insert_grails_user_roles_1}} {{apollo_cmd_insert_grails_user_roles_2}}"