---
- name: "install apache using apt"
  apt:
    name: "apache2"
    state: "latest"
    update_cache: yes

- name: "Enable Apache service at startup"
  systemd:
    name: "apache2"
    state: "started"
    enabled: yes

- name: "Allow Apache HTTP(S) connections"
  ufw:
    rule: allow
    name: 'Apache Full'

