---
- name: change hostname to hostname defined in inventory
  hostname:
    name: "{{ inventory_hostname }}"

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: "127.0.0.1 localhost {{ inventory_hostname }}"
    state: present

- name: disable update_etc_hosts in cloud.cfg to prevent regeneration of /etc/hosts on reboot
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: 'update_etc_hosts'
    line: '# - update_etc_hosts'

- name: set timezone to Australia/Brisbane
  timezone:
    name: Australia/Brisbane

