---
# set facts based on the apollo number 
# i.e. if number entered is 8 full domain name fact will be constructed to apollo-008.genome.edu.au
#
# NOTE: all these facts are "global" for the playbook at run time and can be re-used in subsequent roles

- name: "Print debug message"
  debug:
    msg: "User: {{ ansible_user }}; Env: {{ target_environment }}; Apollo instance number: {{ apollo_instance_number }}"

- name: "Ensure {{ apollo_instance_number }} is converted to a 3-digit string with leading zeros"
  set_fact:
    apollo_number_only: "{{ '%03d' | format(apollo_instance_number|int) }}"

- name: "set fact apollo_full_domain_name and apollo_short_machine_name"
  set_fact:
    apollo_padded_number: "{{ apollo_number_only }}"
    apollo_short_machine_name: "apollo-{{apollo_number_only}}"
    apollo_full_domain_name: "apollo-{{ apollo_number_only }}.genome.edu.au"

- name: "Print full domain name"
  debug: 
    msg: "Full domain = {{ apollo_full_domain_name }} - Machine name = {{ apollo_short_machine_name }} - Instance number = {{ apollo_padded_number }}"

- name: "set fact apollo_custom_full_domain_name"
  set_fact:
    apollo_custom_full_domain_name: "{{ apollo_subdomain_name }}.genome.edu.au"

- name: "Print full custom domain name"
  debug: 
    msg: "Full custom domain name = {{ apollo_custom_full_domain_name }}"

# export the tomcat memory settings for test (small VM) or production (large VM)
- name: "set fact apollo_tomcat_memory_opts from target_tomcat_memory variable"
  set_fact:
    apollo_tomcat_memory_opts: "{{ '-Xms512m -Xmx2g' if target_environment == 'test' else '-Xms8g -Xmx12g' }}"

# define the apollo build version from apollo_version=<VERSION> in inventory file or --extra-vars="...", otherwise use the default as the original Nectar Apollo build
- name: "set apollo_build_version to supplied apollo_version value (eg 2.6.5) or default (2.8.1)"
  set_fact:
#    apollo_build_version: "{{ '{{apollo_version}}' if apollo_version is defined else '2.7.0' }}"
     apollo_build_version: "{{ apollo_version }}"

