---
#This role should not be run by apollo playbook it should be run by a separate playbook
#after manually obtaining ssh certificates that are defined in nginx conf file
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: "ssh"

  tasks:
    - import_role:
        name: apollo-restart-services
