---
- hosts: all
  remote_user: "{{ansible_user}}"
  become: yes
  become_method: sudo
  connection: "ssh"
  
  # This playbook requires to use --limit option 
  tasks:
    - import_role:
        name: "common-configure-shell-logins"
    - import_role:
        name: "common-create-admin-users-logins"
