- hosts: all
  remote_user: ubuntu
  become: yes 
  become_method: sudo
  connection: "ssh"

  vars:
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: present
    docker_users:
      - ubuntu

  tasks:
    - name: Ensure docker does not exist in apt sources - prevents 'Conflicting values' error for keys
      file: 
        path: "{{ item }}"
        state: absent
        force: yes
      with_fileglob:
        - /etc/apt/sources.list.d/docker*
    - import_role:
        name: geerlingguy.docker

