---
- hosts: all
  become: yes
  become_method: sudo
  connection: "ssh"

  # change root password
  # playbook requires password value provided with
  #   --extra-vars="root_password=<PASSWORD>"
  # or via an inventory file containing entries for each host, eg:
  #   apollo-002.genome.edu.au root_password="<PASSWORD>"

  tasks:
    - name: "Change root password"
      user:
        name: root
        update_password: always
        password: "{{ root_password|password_hash('sha512') }}"

