---

- name: "configure prometheus.yml using template with existing apollo servers"
  template:
    src: "prometheus.yml"
    dest: "{{ prometheus_conf }}"
    force: yes
    backup: no
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: "Restart Prometheus and Grafana services"
  service: name={{ item }} state=restarted
  with_items:
    - prometheus
    - grafana-server

