---
- name: "Print full domain name"
  debug: 
    msg: "Full domain = {{ nginx_set_conf_full_domain_name }}"

- name: "set fact nginx_set_conf_config_file_path"
  set_fact:
    nginx_set_conf_config_file_path: "{{ nginx_set_conf_available_dir }}/{{ nginx_set_conf_full_domain_name }}.conf"

- name: "set fact nginx_set_conf_slink_file_path"
  set_fact:
    nginx_set_conf_slink_file_path: "{{ nginx_set_conf_enabled_dir }}/{{ nginx_set_conf_full_domain_name }}.conf"

- name: "set fact nginx_set_conf_site_root_dir"
  set_fact:
    nginx_set_conf_site_root_dir: "/var/www/{{nginx_set_conf_full_domain_name}}/public_html"
    
- name: "set fact nginx_set_conf_index_file_path"
  set_fact:
    nginx_set_conf_index_file_path: "{{ nginx_set_conf_site_root_dir }}/index.html"
    
- name: "set fact nginx_set_conf_default_conf_file_path"
  set_fact:
    nginx_set_conf_default_conf_file_path: "{{ nginx_set_conf_enabled_dir }}/default"

# After setting all facts as required start with required tasks
- name: "Place nginx conf file from template"
  template:
    src: "apollo-00X.genome.edu.au"
    dest: "{{ nginx_set_conf_config_file_path }}"
    force: yes
    backup: no
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  vars:
    template_nginx_domain: "{{ nginx_set_conf_full_domain_name }}"

- name: "Check that dir {{ nginx_set_conf_config_file_path }} exists and register result"
  stat: "path={{ nginx_set_conf_config_file_path }}"
  register: "stat_result"

- name: "Create symbolic link in sites-enabled to available-sites conf exists {{ stat_result.stat.exists }}"
  file:
    src: "{{ nginx_set_conf_config_file_path }}"
    dest: "{{ nginx_set_conf_slink_file_path }}"
    state: link
    force: yes
  when: "stat_result.stat.exists"

- name: "Create site root directory (the 'jbrowse' directory will go under here when Jbrowse is installed)"
  file:
    path: "{{ nginx_set_conf_site_root_dir }}"
    state: directory
    owner: "root"
    group: "www-data"
    mode: "u=rwx,g=rwx,o=rx"

- name: "Change group to www-data and mode to g+rw in /var/www directory"
  file:
    path: "/var/www"
    state: directory
    group: "www-data"
    mode: "g+rw"
    recurse: yes

- name: "Remove default nginx vhost config file - NOTE nginx service has to be restarted after manually obtaining certificates and installing Jbrowse in {{ nginx_set_conf_site_root_dir }}/jbrowse!!!"
  file:
    path: "{{ nginx_set_conf_default_conf_file_path }}"
    state: absent

