---
- name: Install quota packages
  apt:
    pkg:
      - quota
      - quotatool
    state: present

# ref: https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/managing_file_systems/limiting-storage-space-usage-on-ext4-with-quotas_managing-file-systems
- name: enable the ext4 quota feature on device specified by LABEL (external quota files on ext4 are deprecated)
  block:
    - name: "Find the device with LABEL={{ volume_label }}"
      command: blkid -L "{{ volume_label }}"
      register: volume_device
      changed_when: false
      failed_when: false

    - name: "Fail if device with LABEL={{ volume_label }} is not found"
      fail:
        msg: "Device with label {{ volume_label }} not found"
      when: volume_device.stdout == ""

    - name: "unmount {{ mount_point }} to change ext4 quota feature"
      command: umount "{{ mount_point }}"
      #when: volume_device.stdout != ""

    - name: "Enable user and group quotas on the filesystem: use 'tune2fs -Q' to change quota defaults"
      command: tune2fs -O quota "{{ volume_device.stdout }}" # defaults to user and group
      #command: tune2fs -O quota,usrquota,grpquota "{{ volume_device.stdout }}"
      become: yes
      #when: volume_device.stdout != ""
  become: yes

# remount filesystem to enable filesystem quotas and update /etc/fstab
- name: "Remount {{ mount_point }} to enable quota enforcement"
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "LABEL={{ volume_label }}"
    fstype: ext4
    state: mounted
    opts: "{{ mount_opts }},usrquota,grpquota"
    dump: 0
    passno: 2
  become: yes

- name: "Activate quotas on {{ mount_point }}"
  command: "quotaon -v {{ mount_point }}"
  become: yes 

