---
#This role should not be run by apollo playbook it should be run by a separate playbook
#after manually obtaining ssh certificates that are defined in nginx conf file
- name: "Restart tomcat9 service"
  systemd:
    state: "restarted"
    name: "tomcat9"

- name: "Restart nginx service"
  systemd:
    state: "restarted"
    name: "nginx"

- name: "Restart nagios nrpe service"
  systemd:
    state: "restarted"
    name: "nagios-nrpe-server"

# TODO: prometheus is not yet installed - these will need to be uncommented if we use prometheus
#- name: "Restart prometheus node exporter service"
#  systemd:
#    state: "restarted"
#    name: "prometheus-node-exporter"

#- name: "Restart prometheus postgres exporter service"
#  systemd:
#    state: "restarted"
#    name: "prometheus-postgres-exporter"
    
