---
- hosts: all
  become: "yes"
  tasks:
  - import_role:
      name: prometheus-exporters-set-conf

  # The role to be run by this playbook requires the postgres password
  # to be passed through the command line, as follows
  #     --extra-vars="prometheus_postgres_exporter_set_conf_password=jae:Doegahw0"

