---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: "ssh"

  tasks:
    - import_role:
        # Need to install postgres 10 in a docker container in Ubuntu 20.04
        name: common-postgres-docker 
