---
- hosts: all
  become: "yes"

  # This playbook requires to use --limit option 
  tasks:
    - import_role:
        name: add-admin-keys
      vars:
        users:
          - username: "{{ansible_user}}"
            key: files/admin.pub
