---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: "ssh"

  # The roles to be run by this playbook will be applied to the specified servers
  # with, for example
  #   --limit apollo-portal.genome.edu.au
  tasks:
    - import_role:
        name: configure-host
    - import_role:
        name: common-dns-resolv-conf
    - import_role:
        name: add-admin-keys
      vars:
        users:
          - username: "ubuntu"
            key: files/admin.pub
    - import_role:
        name: common-configure-shell-logins
    - import_role:
        name: common-create-admin-users-logins
    - import_role:
        name: web-admin-users-groups
    - import_role:
        name: common-install-fail2ban
    - import_role:
        name: common-configure-ufw
    - import_role:
        name: common-nagios-nrpe
    - import_role:
        name: common-prometheus-node-exporter-ubuntu22
    - import_role:
        name: common-install-utils
    - import_role:
        name: common-certbot-snapd
    - import_role:
        name: common-nginx

