---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: "ssh"

  # The roles to be run by this playbook will be applied to the specified hosts
  # which in this case must be limited to the monitoring server, with, for example
  #   --limit apollo-monitor.genome.edu.au
  tasks:
    - import_role:
        name: common-nginx
    - import_role:
        name: common-certbot-snapd # install here as not installed in base install
    - import_role:
        name: monitor-install-grafana-nginx
    - name: Provide information on next steps for configuring Grafana
      debug:
        msg: |
          Grafana installation is complete.
          To configure Prometheus data sources and provision dashboards,
          run the following using the main ansible inventory (from which host will be extracted):
            ansible-playbook playbook-monitor-refresh-sources-and-dashboards.yml

