---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: "ssh"


  # The role to be run by this playbook requires to enter domain name value through the command line
  # using --extra-vars like in the example below:
  #
  # --extra-vars="postgres_docker_root_password=<enter_in_command_line>"
  # --extra-vars="postgresql_user_password=<enter_in_command_line>"
  # --extra-vars="prometheus_postgres_exporter_set_conf_password=<enter_in_command_line>"
  # --extra-vars="apollo_instance_number=<enter_in_command_line>"
  # --extra-vars="apollo_subdomain_name=<enter_in_command_line>"
  # 
  # i.e.
  # enter_apollo_number_here = 00* or 0** or ***
  # additional_subdomain_name_here = other-relevant-name (without .genome.edu.au)
  #
  tasks:
    - import_role:
        name: apollo-decode-extravars-setfacts-combined
    - import_role:
        name: apollo-pre-build-messages
    - import_role:
        name: configure-host
    # This role is required to be run in Ubuntu 20
    - import_role:
        name: common-dns-resolv-conf
    - import_role:
        name: add-admin-keys
      vars:
        users:
          - username: "ubuntu"
            key: files/admin.pub
    - import_role:
        name: common-configure-shell-logins
    - import_role:
        name: common-create-admin-users-logins
    - import_role:
        name: common-install-fail2ban
    - import_role:
        name: common-configure-ufw
    - import_role:
        name: "common-copy-exec-to-bin"
    - import_role:
        name: apollo-dependencies
    - import_role:
       # Need to install postgres 10 in a docker container in Ubuntu 20.04
        name: common-docker-postgres
    - import_role:
        # Need to use snapd to install certbot in Ubuntu 20.04
        name: common-certbot-snapd
    - import_role:
        name: common-nginx
    - import_role:
        name: common-open-jdk
    - import_role:
        name: common-tomcat-ubuntu20
    - import_role:
        name: apollo-add-nfs-mount-to-fstab
    - import_role:
        name: apollo-copy-war-ubuntu20
    - import_role:
        name: apollo-create-apollo-data-dir
    - import_role:
        name: apollo-deploy-war
    - import_role:
        name: apollo-docker-postgres
    - import_role:
        name: apollo-set-tools-path
    - import_role:
        name: common-nagios-nrpe
    - import_role:
        name: prometheus-exporters-ubuntu20
    - import_role:
        name: prometheus-exporters-set-conf
    - import_role:
        name: common-webdav
    - import_role:
        name: apollo-restart-tomcat
    - import_role:
        name: apollo-restart-nginx
    - import_role:
        name: apollo-create-admin-users-logins
    - import_role:
        name: apollo-create-cli-user
    - import_role:
        name: apollo-setup-user-home-dir
    # the following steps were from playbook-apollo-ubuntu20-combined-2.yml
    - import_role:
        name: apollo-certbot-create-cert
    - import_role:
        name: apollo-certbot-add-domain
    - import_role:
        name: common-nginx-set-conf
    - import_role:
        name: common-nginx-add-domain
    # add a delay here to ensure that tomcat (on restart) has finished
    # extracting apollo from war file and apollo grails app has built database schema
    # before inserting user
    - import_role:
        name: apollo-delay-for-grails-schema-completion
    - import_role:
        name: apollo-docker-postgres-create-admin
    - import_role:
        name: apollo-docker-configure-backup
    - import_role:
        name: apollo-restart-services
    - import_role:
        name: update-base-ubuntu
    - import_role:
        name: apollo-post-build-messages

 
