---
- hosts:
  - newportalvms
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: "ssh"
  roles:
    - role: geerlingguy.postgresql
      become: true
    - apollo-portal
    - apollo-portal-configure-backup
