---
- hosts: all
  #remote_user: "{{ansible_user}}" # requires inventory to define ansible_user=ubuntu
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: "ssh"
  
  # change apollo application password for existing apollo user
  # playbook requires username and password values provided with for example
  #   ansible-playbook playbook-apollo-set-user-password.yml \
  #     --extra-vars="apollo_username=ops@qfab.org" \
  #     --extra-vars="apollo_password=<PASSWORD>" \
  #     --limit apollo-002.genome.edu.au
  # or using an inventory file containing username and password pairs for each host, eg:
  #   ansible-playbook playbook-apollo-set-user-password.yml \
  #     --inventory-file apolloadminpasswdvms.inventory \
  #     --limit chpasswdvms
  # with apolloadminpasswdvms.inventory containing
  #   [chpasswdvms]
  #   apollo-002.genome.edu.au apollo_username="ops@qfab.org" apollo_password="<SECRET>"
  #

  tasks:
    - import_role:
        name: "apollo-docker-postgres-set-user-password"

