---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: "ssh"

  # The roles to be run by this playbook will be applied to the specified servers
  # with, for example
  #   --limit apollo-sandpit.genome.edu.au
  tasks:
    - import_role:
        name: apollo-decode-extravars-setfacts-combined
    - import_role:
        name: common-conf-hostname-tz
    - import_role:
        name: common-conf-update_etc_hosts
    - import_role:
        name: common-add-admin-keys
    - import_role:
        name: common-configure-shell-logins
    - import_role:
        name: common-create-admin-users-logins
    - import_role:
        name: common-install-fail2ban
    - import_role:
        name: common-configure-ufw
    - import_role:
        name: apollo-openjdk8
    - import_role:
        name: apollo-tomcat9-ubuntu
    - import_role:
       # Need to install postgres 10 in a docker container in Ubuntu >= 20.04
        name: apollo-install-docker-postgres
    - import_role:
        name: common-nagios-nrpe
    - import_role:
        name: common-prometheus-node-exporter-ubuntu
    - import_role:
        name: common-install-utils
    - import_role:
        name: apollo-dependencies
    - import_role:
        name: apollo-build-dependencies
    - import_role: 
        # Use snapd to install certbot in Ubuntu >= 20.04
        name: common-certbot-snapd
    - import_role:
        name: common-nginx
    - import_role:
        name: apollo-create-cli-user
    - import_role:
        name: apollo-add-nfs-mount-to-fstab
    - import_role:
        name: apollo-certbot-create-cert
    - import_role:
        name: apollo-certbot-add-domain
    - import_role:
        name: apollo-nginx-set-conf
    - import_role:
        name: common-nginx-add-domain
    - import_role:
        name: apollo-docker-postgres-createdb
    # from here won't work until apollo is up and running on the sandpit, so need to be run with tags
    # run with --tags backup
    - import_role:
        name: apollo-docker-configure-backup
      tags: [ never, backup ]
    # run with --tags admin
    - import_role:
        name: apollo-docker-postgres-insert-admin
      tags: [ never, admin ]

