---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: "ssh"


  # The role to be run by this playbook requires to enter domain name value through the command line
  # using --extra-vars like in the example below:
  #
  # --extra-vars="postgres_docker_root_password=<enter_in_command_line>"
  # --extra-vars="postgresql_user_password=<enter_in_command_line>"
  # --extra-vars="prometheus_postgres_exporter_set_conf_password=<enter_in_command_line>"
  # --extra-vars="apollo_instance_number=<enter_in_command_line>"
  # --extra-vars="apollo_subdomain_name=<enter_in_command_line>"
  # 
  # i.e.
  # enter_apollo_number_here = 00* or 0** or ***
  # additional_subdomain_name_here = other-relevant-name (without .genome.edu.au)
  #
  tasks:
    - import_role:
        name: apollo-decode-extravars-setfacts-combined
    - import_role:
        name: apollo-pre-build-messages
    - import_role:
        name: configure-host
    # This role is required to be run in Ubuntu 20
    - import_role:
        name: common-dns-resolv-conf
    - import_role:
        name: add-admin-keys
      vars:
        users:
          - username: "ubuntu"
            key: files/admin.pub
    - import_role:
        name: common-configure-shell-logins
    - import_role:
        name: common-create-admin-users-logins
    - import_role:
        name: common-install-fail2ban
    - import_role:
        name: common-configure-ufw
    - import_role:
        # Need to use snapd to install certbot in Ubuntu 20.04
        name: common-certbot-snapd
    - import_role:
        name: common-nginx
    - import_role:
        name: jbrowse-dependencies
    - import_role:
        name: jbrowse-install-nodejs
    - import_role:
        name: jbrowse-build-jbrowse
    - import_role:
        name: apollo-add-nfs-mount-to-fstab
    - import_role:
        name: common-nagios-nrpe
    - import_role:
        name: prometheus-exporters-ubuntu
    - import_role:
        name: prometheus-exporters-set-conf
    - import_role:
        name: common-webdav

    - import_role:
        name: jbrowse-admin-users-groups
    - import_role:
        name: apollo-create-cli-user
    - import_role:
        name: apollo-setup-user-home-dir
    # the following steps were from playbook-apollo-ubuntu20-combined-2.yml
    - import_role:
        name: apollo-certbot-create-cert
    - import_role:
        name: apollo-certbot-add-domain
    - import_role:
        name: jbrowse-nginx-set-conf
    - import_role:
        name: common-nginx-add-domain
    - import_role:
        name: common-restart-nginx

    - import_role:
        name: update-base-ubuntu
    - import_role:
        name: jbrowse-post-build-messages

