# apollo-client (nginx) Dockerfile
FROM nginx:alpine

ARG JBROWSE_VERSION
ARG APOLLO_VERSION

# Tools we need to fetch & unpack assets
RUN apk add --no-cache wget unzip tar

# NGINX config
COPY apollo-client.nginx.conf /etc/nginx/conf.d/default.conf

# Static site root
WORKDIR /usr/share/nginx/html

# Fetch JBrowse + Apollo plugin + SO JSON (same as Apache version)
RUN set -eux; \
    wget -O jbrowse-web.zip "https://github.com/GMOD/jbrowse-components/releases/download/v${JBROWSE_VERSION}/jbrowse-web-v${JBROWSE_VERSION}.zip"; \
    unzip -o jbrowse-web.zip; \
    rm jbrowse-web.zip; \
    wget -q "https://registry.npmjs.org/@apollo-annotation/jbrowse-plugin-apollo/-/jbrowse-plugin-apollo-${APOLLO_VERSION}.tgz" -O - \
      | tar --extract --gzip --file=- --strip=2 package/dist/jbrowse-plugin-apollo.umd.production.min.js; \
    mv jbrowse-plugin-apollo.umd.production.min.js apollo.js; \
    wget -q "https://github.com/The-Sequence-Ontology/SO-Ontologies/raw/refs/heads/master/Ontology_Files/so.json" -O sequence_ontology.json

# NGINX will listen on 80 by default
EXPOSE 80

# (nginx:alpine already runs: nginx -g 'daemon off;')

