---
# set facts based on the apollo number 
# i.e. if number entered is 8 full domain name fact will be constructed to apollo-008.genome.edu.au
#
# NOTE: all these facts are "global" for the playbook at run time and can be re-used in subsequent roles
#

- name: "Print debug message"
  debug: 
    msg: "User: {{ ansible_user }}; Env: {{ target_environment }}; Apollo instance number: {{apollo_instance_number}}"

- name: "Ensure {{ apollo_instance_number }} is converted to a 3-digit string with leading zeros"
  set_fact:
    apollo_number_only: "{{ '%03d' | format(apollo_instance_number|int) }}"

- name: "set fact apollo_full_domain_name and apollo_short_machine_name"
  set_fact:
    apollo_padded_number: "{{ apollo_number_only }}"
    apollo_short_machine_name: "apollo-{{apollo_number_only}}"
    apollo_full_domain_name: "apollo-{{ apollo_number_only }}.genome.edu.au"

- name: "Print full domain name"
  debug: 
    msg: "Full domain = {{apollo_full_domain_name}} - Machine name = {{apollo_short_machine_name}} - Instance number = {{apollo_padded_number}}"

- name: "Determine if root disk is /dev/vda (based on setting in inventory file)"
  set_fact:
    root_on_vda: "{{ 'true' if apollo_root_disk_device == '/dev/vda2' else 'false' }}"

- name: Print root disk information
  debug:
    msg: "Root disk is {{ apollo_root_disk_device }} - root_on_vda: {{ root_on_vda }}"

# when target_environment is test modify test nagios and grafana config files in /tmp
- name: "set fact override config locations if apollo_evironment is test"
  set_fact:
    nagios_conf_path: "{{ '/tmp' if target_environment == 'test' else '/etc/nagios4/servers' }}"
    grafana_conf_path: "{{ '/tmp' if target_environment == 'test' else '/etc/prometheus' }}"

