---
- name: "Place nginx conf file from template"
  template:
    src: "apollo-00X.genome.edu.au"
    dest: "{{nginx_set_conf_config_file_path}}"
    force: yes
    backup: no
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  vars:
    template_nginx_domain: "{{nginx_set_conf_domain_name}}"

- name: "Check that dir {{nginx_set_conf_config_file_path}} exists and register result"
  stat: "path={{nginx_set_conf_config_file_path}}"
  register: "stat_result"

- name: "Create symbolic link in sites-enabled to available-sites conf exists {{stat_result.stat.exists}}"
  file:
    src: "{{nginx_set_conf_config_file_path}}"
    dest: "{{nginx_set_conf_slink_file_path}}"
    state: link
    force: yes
  when: "stat_result.stat.exists"

- name: "Create site root directory"
  file:
    path: "{{nginx_set_conf_site_root_dir}}"
    state: directory
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

- name: "Place index html file from template"
  template:
    src: "index.html"
    dest: "{{nginx_set_conf_index_file_path}}"
    force: yes
    backup: no
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"

- name: "Create symbolic link for index html"
  file:
    src: "{{nginx_set_conf_root_index}}"
    dest: "{{nginx_set_conf_index_file_path}}"
    state: link
    force: yes

- name: "Change group to www-data and mode to g+w in /var/www directory"
  file:
    path: "/var/www"
    state: directory
    group: "www-data"
    mode: "g+w"
    recurse: yes

- name: "Remove default nginx vhost config file - NOTE nginx service has to be restarted after manually obtaining certificates!!!"
  file:
    path: "{{nginx_set_conf_default_conf_file_path}}"
    state: absent


