---
- name: "import vars"
  include_vars:
    file: users.yml

- name: "Create web administrator user accounts"
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    uid: "{{ item.uid }}"
    state: "present"
  with_items: "{{ users }}"

- name: "Make these users home directories private"
  file:
    path: "//home/{{ item.username }}"
    state: directory
    mode: 0700
  with_items: "{{ users }}"

- name: "Add authorized key from file for login users"
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', item.key) }}"
  with_items: "{{ login_users }}"

- name: "adding login_users to apollo_admin (allows login) and www-data groups"
  user:
    name: "{{ item.username }}"
    groups: 
    - "apollo_admin" 
    - "www-data" 
    append: yes
  with_items: "{{ login_users }}"

- name: "adding sudo_users to OS-specific sudo group"
  user:
    name: "{{ item }}"
    groups: 
    - "{{ admin_group }}" 
    append: yes
  with_items: "{{ sudo_users }}"

- name: "adding backup_user to www-data group"
  user:
    name: "backup_user"
    groups: "www-data" 
    append: yes

- name: "Remove login privs from inactive users"
  user: 
    name: "{{ item }}"
    shell: /sbin/nologin
  with_items: "{{ inactive_users }}"

- name: "Remove old user accounts in remove_users"
  user:
    name: "{{ item }}"
    state: "absent"
    remove: yes
    force: yes
  with_items: "{{ remove_users }}"

