---
- name: "import vars"
  include_vars:
    file: users.yml

- name: "Add authorized key from file"
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', item.key) }}"
    state: "present"
  with_items: "{{ users }}"
