---
- name: "Remove any other certbot packages"
  apt:
    name:
      - "certbot"
      - "python3-certbot-nginx"
    state: absent

- name: "Install software properties common"
  apt:
    name: "software-properties-common"
    state: present

- name: "Install ppa certbot repository"
  apt_repository:
    validate_certs: no
    repo: "{{ certbot_apt_repo }}"
    state: present

- name: "Install certbot packages"
  apt:
    name:
      - "certbot"
      - "python3-certbot-nginx"
    state: present

- name: "Perform apt update"
  apt:
    update_cache: yes

- name: "Run certbot renew as a dry run to create letsencrypt/live directory"
  command: certbot --dry-run renew
  args:
    creates: "{{ certbot_ssl_path }}"
