---
- name: "Check that dir {{nginx_current_config_file_path}} exists and register result"
  stat: "path={{nginx_current_config_file_path}}"
  register: "stat_result"

- name: "Copy {{nginx_current_config_file_path}} to {{nginx_add_conf_config_file_path}} stat_result.stat.exists = {{stat_result.stat.exists}}"
  command: "cp {{nginx_current_config_file_path}} {{nginx_add_conf_config_file_path}}"
  when: "stat_result.stat.exists"

- name: "set fact"
  set_fact:
    simple_domain_name: "{{ nginx_conf_domain_name.split('.') }}"

- name: "debug"
  debug:
    msg: "{{simple_domain_name[0]}}"

- name: "set fact"
  set_fact:
    simple_add_domain_name: "{{ nginx_add_conf_full_domain_name.split('.') }}"

- name: "debug"
  debug:
    msg: "{{simple_add_domain_name[0]}}"

- name: "Replace domain name in new nginx config file"
  replace:
    path: "{{nginx_add_conf_config_file_path}}"
    regexp: "server_name[\\s+\\t+]*{{simple_domain_name[0]}}"
    replace: "server_name {{simple_add_domain_name[0]}}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  when: "stat_result.stat.exists"

- name: "Create symbolic link in enabled-sites to available-sites for new config file"
  file:
    src: "{{nginx_add_conf_config_file_path}}"
    dest: "{{nginx_add_conf_slink_file_path}}"
    state: link
    force: yes
  when: "stat_result.stat.exists"

