---
- name: "Install Ubuntu packages for the Nagios 4 monitoring server"
  apt:
    pkg:
      - nagios4
      - nagios-nrpe-server
      - nagios-nrpe-plugin
      - nagios-plugins-contrib
    state: present
    update_cache: yes

- name: "Install python-passlib for the htpasswd module"
  apt:
    name: "python-passlib"
    state: present
    update_cache: yes

- name: "Enable the Apache authz_groupfile, auth_digest and rewrite modules"
  command: "{{ item }}"
  with_items:
    - a2enmod authz_groupfile
    - a2enmod auth_digest
    - a2enmod rewrite

## delete /etc/nagios4/htdigest.users
#- name: "Remove htdigest file if it exists - to prevent issues with htpasswd file creation"
#  file:
#    path: /etc/nagios4/htdigest.users
#    state: absent
#
## note htpasswd module doesn't support realm, and htdigest command doesn't support non-interactive use
#- name: "Create htpasswd file with Nagios admin username and password for authentication"
#  htpasswd: 
#    path: /etc/nagios4/htdigest.users
#    name: "{{ nagios_username }}"
#    password: "{{ nagios_password }}"

- name: "create new htdigest file with specified username and password"
  shell: >
    (echo -n "{{nagios_username}}:Nagios4:" && echo -n "{{nagios_username}}:Nagios4:{{nagios_password}}" | md5sum - | cut -d' ' -f1) > /etc/nagios4/htdigest.users

- name: "Place apache2.conf template in {{ nagios_apache_conf_path }} directory"
  template:
    src: "apache2.conf"
    dest: "{{ nagios_apache_conf_path }}"
    force: yes
    backup: no
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: "Configure Nagios to use authentication"
  lineinfile:
    path: "/etc/nagios4/cgi.cfg"
    regexp: '^use_authentication'
    line: "use_authentication=1"
    state: present

- name: "Restart Nagios and Apache services"
  service: name={{ item }} state=restarted
  with_items:
    - nagios4
    - apache2

- name: "Enable Nagios service"
  systemd:
    name: "nagios4"
    state: "started"
    enabled: yes

#- name: "Create symbolic link of /etc/nagios to /etc/nagios4 for backwards compatibility with existing Apollo creation scripts"
#  file:
#    src: /etc/nagios4
#    dest: /etc/nagios
#    state: link
#    force: yes

