---
- name: Install NFS server and utilities"
  apt:
    pkg:
      - nfs-common
      - nfs-kernel-server
    state: present

- name: Ensure NFS service is running
  service:
    name: nfs-kernel-server
    enabled: true
    state: started

- name: Allow NFS port (2049) from 192.168.0.0/24 (TCP)
  ufw:
    rule: allow
    port: '2049'
    proto: tcp
    src: '192.168.0.0/24'

- name: Allow RPCBind port (111) from 192.168.0.0/24 (UDP/TCP)
  ufw:
    rule: allow
    port: '111'
    proto: "{{ item }}"
    src: '192.168.0.0/24'
  with_items:
    - 'udp'
    - 'tcp'

- name: Create the mount point directory for bind mount
  file:
    path: "{{ bind_point }}"
    state: directory
  become: yes

# create bind mount and add entry to /etc/fstab:
#    {{ mount_point }}        {{ bind_point }}    none    bind        0 0
- name: "Create bind mount for {{ mount_point }} on {{ bind_point }}"
  ansible.posix.mount:
    path: "{{ bind_point }}"
    src: "{{ mount_point }}"
    fstype: none
    state: mounted
    opts: bind
  become: yes

- name: "Ensure export root directory {{ export_root }} exists and create if it doesn't"
  file:
    path: "{{ export_root }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Define root of the NFSv4 export tree
  blockinfile:
    path: /etc/exports
    insertafter: EOF
    block: |
      # fsid=0 defines this as the root of the NFSv4 export tree.
      # All exports need to be directories under this root
      {{ export_root }} 192.168.0.0/24(rw,fsid=0,no_subtree_check,sync)
    marker: "# {mark} ANSIBLE MANAGED BLOCK (role nfs-install-server)"
  become: yes

- name: update NFS exports from /etc/exports
  command: exportfs -ra
  become: yes
  become_user: root

