---
- hosts: 
   - ubuntutestvms
   - apollovms
   - otherubuntuvms
  remote_user: "{{ansible_user}}"
  become: yes
  become_method: sudo
  connection: "ssh"
  
  handlers:
  - name: "Restart sshd"
    service:
      name: "sshd"
      state: "restarted"
      
  tasks:
    - import_role:
        name: "setup-admin-users-groups-logins"