---
- name: "Include utility packages for troubleshooting"
  include_vars:
    file: "util_packages.yml"

- name: "install utility packages"
  apt:
    pkg: "{{ util_packages }}"
    state: present
    update_cache: yes


