---
- name: "Install tomcat {{ tomcat_version }}"
  apt:
    name: "tomcat{{ tomcat_version }}"
    state: "present"
    update_cache: yes

- name: "Place tomcat{{ tomcat_version }} template in /etc/default directory"
  template:
    src: "{{ tomcat_template_file }}"
    dest: "{{ tomcat_default_file_path }}"
    force: yes
    backup: no
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: "Remove ROOT directory"
  file:
    path: "{{ tomcat_root_file_path }}"
    state: absent
