---
- name: "Include monitoring server variables"
  include_vars:
    file: "prometheus_exporters.yml"

# deprecated
#- name: "Add key for prometheus packages"
#  apt_key:
#    url: "{{ prometheus_url_key }}"
#    state: present

- name: "Install prometheus exporters"
  apt:
    name: "{{ prometheus_exporters }}"
    state: present
    update_cache: yes

- name: "Allow connections to prometheus exporters from grafana server"
  ufw:
    rule: allow
    proto: tcp
    port: '{{ item }}'
    src: '{{ grafana_server }}'
  with_items:
    - '9100'
    - '9187'

