---
- name: "Create apollo CLI user account {{ create_user_name }} with UID {{ create_user_id }}"
  user:
    name: "{{ create_user_name }}"
    shell: "/bin/bash"
    uid: "{{ create_user_id }}"
    state: "present"

# needed where apollo organism was created on pawsey using path via symlink in home directory
# also simplifies admin, but does mean that tomcat can read user's home directory
- name: "Make the apollo CLI user home directory /home/{{ create_user_name }} world-readable"
  file:
    path: "/home/{{ create_user_name }}"
    mode: "0755"
    state: directory

- name: "Read /etc/ssh/sshd_config content"
  shell:
    cmd: "cat /etc/ssh/sshd_config"
  register: var_sshd_config

- set_fact:
    var_regex_sshd_config: "{{ var_sshd_config.stdout | regex_search('AllowGroups.*') }}"

- name: "Print AllowGroups entry from sshd_config"
  debug:
    msg: "{{ var_regex_sshd_config}}"

- set_fact:
    new_allowgroups_line: |
      {% set groups = var_regex_sshd_config | regex_replace('^AllowGroups\\s+', '') %}
      {% if create_user_name not in groups %}
      AllowGroups {{ groups }} {{ create_user_name }}
      {% else %}
      AllowGroups {{ groups }}
      {% endif %}

- name: "Append the CLI user's group (same as username) to /etc/ssh/sshd_config AllowGroups"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^AllowGroups"
    line: "{{ new_allowgroups_line }}"
    state: present
  notify:
    - Restart ssh
