---
- name: "Print user name and user id to be created"
  debug: 
    msg: "User Name = {{create_user_name}} - User Id = {{create_user_id}}"

- name: "Create apollo user account"
  user:
    name: "{{create_user_name}}"
    shell: "/bin/bash"
    uid: "{{create_user_id}}"
    state: "present"

- name: "Adding user to group"
  user:
    name: "{{create_user_name}}"
    groups: "{{create_user_name}}"
    append: yes

- name: "Read /etc/ssh/sshd_config content"
  shell:
    cmd: "cat /etc/ssh/sshd_config"
  register: var_sshd_config

- set_fact:
    var_regex_sshd_config: "{{ var_sshd_config.stdout | regex_search('AllowGroups.*') }}"

- name: "Print"
  debug:
    msg: "Resultado de regex = {{ var_regex_sshd_config}}"

- name: "Add groups to /etc/ssh/sshd_config AllowGroups"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^AllowGroups"
    line: "{{var_regex_sshd_config}} {{create_user_name}}"
    state: present
  notify:
    - Restart sshd
