---
- name: "Create apollo CLI user account {{ create_user_name }} with UID {{ create_user_id }}"
  user:
    name: "{{ create_user_name }}"
    shell: "/bin/bash"
    uid: "{{ create_user_id }}"
    state: "present"

- name: "Read /etc/ssh/sshd_config content"
  shell:
    cmd: "cat /etc/ssh/sshd_config"
  register: var_sshd_config

- set_fact:
    var_regex_sshd_config: "{{ var_sshd_config.stdout | regex_search('AllowGroups.*') }}"

- name: "Print AllowGroups entry from sshd_config"
  debug:
    msg: "{{ var_regex_sshd_config}}"

- set_fact:
    new_allowgroups_line: |
      {% if create_user_name not in var_regex_sshd_config %}
        {{ var_regex_sshd_config }} {{ create_user_name }}
      {% else %}
        {{ var_regex_sshd_config }}
      {% endif %}

- name: "Append the CLI user's group (same as username) to /etc/ssh/sshd_config AllowGroups"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^AllowGroups"
    line: "{{ new_allowgroups_line }}"
    state: present
  notify:
    - Restart ssh
