- hosts: all
  become: 'yes'
  vars:
    users:
      - username: "ubuntu"
        key: files/admin.pub
  tasks:
  - name: "Add authorized key from file"
    authorized_key:
      user: "{{ item.username }}"
      key: "{{ lookup('file', item.key) }}"
    with_items: "{{ users }}"

