---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: "ssh"

  tasks:
    - import_role:
        name: "common-copy-exec-to-bin"
    - import_role:
        name: apollo-dependencies
    - import_role:
        name: common-certbot
    - import_role:
        name: common-nginx
    - import_role:
        name: common-open-jdk
    - import_role:
        name: common-tomcat
    - import_role:
        name: common-postgresql
    - import_role:
        name: apollo-copy-war
    - import_role:
        name: apollo-deploy-war
    - import_role:
        name: common-nagios-nrpe

