---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: "ssh"


  # The role to be run by this playbook requires to enter domain name value through the command line
  # using --extra-vars like in the example below:
  #
  # --extra-vars="postgres_docker_root_password=<enter_in_command_line>"
  # --extra-vars="postgresql_user_password=<enter_in_command_line>"
  # --extra-vars="prometheus_postgres_exporter_set_conf_password=<enter_in_command_line>"
  # --extra-vars="apollo_instance_number=<enter_in_command_line>"
  # --extra-vars="apollo_subdomain_name=<enter_in_command_line>"
  # 
  # i.e.
  # enter_apollo_number_here = 00* or 0** or ***
  # additional_subdomain_name_here = other-relevant-name (without .genome.edu.au)
  #
  tasks:
    - import_role:
        name: apollo-decode-extravars-setfacts
      vars:
        apollo_environment: "test"
        apollo_dev_domain: "ubuntu20-test.genome.edu.au"
    - import_role:
        name: configure-host
    # This role is required to be run in Ubuntu 20
    - import_role:
        name: common-dns-resolv-conf
    - import_role:
        name: add-admin-keys
      vars:
        users:
          - username: "ubuntu"
            key: files/admin.pub
    - import_role:
        name: "common-copy-exec-to-bin"
    - import_role:
        name: apollo-dependencies
    - import_role:
       # Need to install postgres 10 in a docker container in Ubuntu 20.04
        name: common-docker-postgres
    - import_role:
        # Need to use snapd to install certbot in Ubuntu 20.04
        name: common-certbot-snapd
    - import_role:
        name: common-nginx
    - import_role:
        name: common-open-jdk
    - import_role:
        name: common-tomcat-ubuntu20
    - import_role:
        name: apollo-copy-war-ubuntu20
    - import_role:
        name: apollo-create-apollo-data-dir
    - import_role:
        name: apollo-deploy-war
    - import_role:
        name: apollo-docker-postgres
    - import_role:
        name: common-nagios-nrpe
    - import_role:
        name: configure-ufw
    - import_role:
        name: prometheus-exporters-ubuntu20
    - import_role:
        name: prometheus-exporters-set-conf
    - import_role:
        name: common-webdav
    - import_role:
        name: apollo-restart-tomcat
    - import_role:
        name: apollo-restart-nginx
    - import_role:
        name: "create-admin-users-groups-logins"
    - import_role:
        name: apollo-create-user
    
