---
- name: "add Apollo tools path to user environment"
  copy:
    dest: /etc/profile.d/apollo-tools-path.sh
    force: no
    content: 'PATH=$PATH:{{ apollo_tools_path }}'
    owner: root
    group: root
    mode: "u=rw,g=r,o=r" 

