---
- name: "import vars"
  include_vars:
    file: users.yml

- name: "adding backup_user to www-data group"
  user:
    name: "backup_user"
    groups: "www-data" 
    append: yes

- name: "ensure admin's accounts have shell login enabled (for accounts disabled on other VMs)"
  user:
    name: "{{ item }}"
    shell: /bin/bash
  with_items: "{{ admin_users }}"

- name: "adding admin_users to apollo_admin (allows login) and www-data groups"
  user:
    name: "{{ item }}"
    groups: 
    - "apollo_admin" 
    - "www-data" 
    append: yes
  with_items: "{{ admin_users }}"

- name: "adding sudo_users to OS-specific sudo group"
  user:
    name: "{{ item }}"
    groups:
    - "{{ admin_group }}"
    append: yes
  with_items: "{{ sudo_users }}"

