
users:
  - username: "backup_user"
    comment: ""
    uid: 9999
  - username: "j.lee"
    comment: "Justin Lee"
    uid: 19529
  - username: "n.rhodes"
    comment: "Nick Rhodes"
    uid: 12143
  - username: "m.thang"
    comment: "Mike Thang"
    uid: 13486
  - username: "a.bulgaris"
    comment: "Alejandro Bulgaris"
    uid: 34928
  - username: "c.bromhead"
    comment: "Catherine Bromhead"
    uid: 37841
  - username: "g.price"
    comment: "Gareth Price"
    uid: 27474


login_users:
  - username: "backup_user"
    key: files/backup_user.pub
  - username: "j.lee"
    key: files/j.lee.pub
  - username: "n.rhodes"
    key: files/n.rhodes.pub
  - username: "c.bromhead"
    key: files/c.bromhead.pub
#  - username: "g.price"
#    key: files/g.price.pub
#  - username: "m.thang"
#    key: files/m.thang.pub
#  - username: "a.bulgaris"
#    key: files/a.bulgaris.pub

sudo_users:
  - "j.lee"
  - "n.rhodes"
  - "c.bromhead"

# note this list MUST have at least 1 entry or the associated task fails!!!
# the inactive user will be created if not already defined (with the next available UID)
# but can be deleted by adding to the remove_users list
inactive_users:
  - "a.bulgaris"
#  - "m.thang"

remove_users:
  - "a.bulgaris"
  - "g.price"

